### ISSUE TITLE
Your RSS feed links are slightly broken

### ISSUE THREAD

**Issue by thisiswhereitype** [BekahHW/BekahHW.github.io#5]
e.g. https://bekahhw.github.io/blog///blog/2020/02/28/Bootcamp-Isn't-All-Happy-Face-Emojis

in https://bekahhw.github.io/feed.xml

**Comment by BekahHW** [comment]
Thanks! Trying to figure it out.

**Comment by thisiswhereitype** [comment]
Looks fixed
